window.OTHENTIK_PRODUCTS = [{id:1,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p1.jpeg'},
{id:2,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p2.jpeg'},
{id:3,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p3.jpeg'},
{id:4,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p4.jpeg'},
{id:5,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p5.jpeg'},
{id:6,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p6.jpeg'},
{id:7,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p7.jpeg'},
{id:8,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p8.jpeg'},
{id:9,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p9.jpeg'},
{id:10,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p10.jpeg'},
{id:11,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p11.jpeg'},
{id:12,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p12.jpeg'},
{id:13,name:'Coupe dame',price:8500,category:'Coupes dames',detail:'Coupe dame • style court',image:'images/p13.jpeg'},
{id:14,name:'Blend Hair Boucles Water Wave',price:35000,category:'Perruques',detail:'Boucles Water Wave',image:'images/p14.jpeg'},
{id:15,name:'Coupe carrée Taille 10 SDD',price:25000,category:'Coupes carrées',detail:'Taille 10 · qualité SDD',image:'images/p15.jpeg'},
{id:16,name:'Coupe carrée Taille 10 SDD',price:25000,category:'Coupes carrées',detail:'Taille 10 · qualité SDD',image:'images/p16.jpeg'},
{id:17,name:'Coupe carrée Taille 10 SDD',price:25000,category:'Coupes carrées',detail:'Taille 10 · qualité SDD',image:'images/p17.jpeg'},
{id:18,name:'Coupe carrée Taille 10 SDD',price:25000,category:'Coupes carrées',detail:'Taille 10 · qualité SDD',image:'images/p18.jpeg'},
{id:19,name:'Coupe carrée Taille 10 SDD',price:25000,category:'Coupes carrées',detail:'Taille 10 · qualité SDD',image:'images/p19.jpeg'},
{id:20,name:'Coupe carrée Taille 10 SDD',price:25000,category:'Coupes carrées',detail:'Taille 10 · qualité SDD',image:'images/p20.jpeg'},
{id:21,name:'Coupe carrée Taille 10 SDD',price:25000,category:'Coupes carrées',detail:'Taille 10 · qualité SDD',image:'images/p21.jpeg'},
{id:22,name:'Coupe Jerry bouclée',price:20000,category:'Jerry bouclées',detail:'Taille 14 · boucles Jerry',image:'images/p22.jpeg'},
{id:23,name:'Coupe Jerry bouclée',price:20000,category:'Jerry bouclées',detail:'Taille 14 · boucles Jerry',image:'images/p23.jpeg'},
{id:24,name:'Coupe Jerry bouclée',price:20000,category:'Jerry bouclées',detail:'Taille 14 · boucles Jerry',image:'images/p24.jpeg'},
{id:25,name:'Coupe Jerry bouclée',price:20000,category:'Jerry bouclées',detail:'Taille 14 · boucles Jerry',image:'images/p25.jpeg'},
{id:26,name:'Coupe Jerry bouclée',price:20000,category:'Jerry bouclées',detail:'Taille 14 · boucles Jerry',image:'images/p26.jpeg'},
{id:27,name:'Coupe Jerry bouclée',price:20000,category:'Jerry bouclées',detail:'Taille 14 · boucles Jerry',image:'images/p27.jpeg'}];
